### ISSUE TITLE
factor-bundle cannot be located by Browserify when using common option

### ISSUE THREAD

**Issue by eggyal** [atomify/atomify-js#61]
When invoking with `common: true`, Browserify is unable to find `factor-bundle` (being a dependency of `atomify-js`, it's amongst its parent's `node_modules` and therefore cannot be resolved):

    Error: Cannot find module 'factor-bundle' from '/path/to/project'
        at Function.module.exports (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/resolve/lib/sync.js:33:11)
        at Browserify.plugin (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/index.js:291:29)
        at atomifyJs (/path/to/project/node_modules/atomify/node_modules/atomify-js/index.js:224:7)
    ...

    $ find /path/to/project/node_modules -name factor-bundle
    /path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/.bin/factor-bundle
    /path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/factor-bundle

**Comment by joeybaker** [comment]
hmmm… that's interesting. Can you share your atomify config/cli command @eggyal?

**Comment by eggyal** [comment]
I am invoking `gulp js` with the following `Gulpfile.js`:

	'use strict';

	var gulp = require('gulp'),
	    livereload = require('gulp-livereload'),
	    js = require('atomify').js;

	function string_src(filename, string) {
		var src = require('stream').Readable({ objectMode: true });
		src._read = function () {
			this.push(new gutil.File({
				cwd     : "",
				base    : "",
				path    : filename,
				contents: new Buffer(string)
			}));
			this.push(null)
		}
		return src;
	}

	gulp.task('js', function () {
		var dir = './web/js/';

		js.emitter.on('entry', function(content, bundleName) {
			return string_src(bundleName, content)
			.pipe(gulp.dest(dir))
			.pipe(livereload());
		});

		return js({
			entries: [
				'./app/js/test1.js',
				'./app/js/test2.js'
			],
			common : true,
			debug  : true,
			minify : false,
			watch  : true,
			assets : {
				dest  : "./web/assets",
				prefix: "assets/"
			}
		}).pipe(gulp.dest(dir))
		  .pipe(livereload());
	});

**Comment by joeybaker** [comment]
hmmm… okay. @eggyal can you try this branch and see if it fixes things for you? https://github.com/atomify/atomify-js/tree/directlyRequireFactorBundle

**Comment by eggyal** [comment]
Afraid not—

> path.js:439
>       throw new TypeError('Arguments to path.resolve must be strings');

**Comment by joeybaker** [comment]
Hmmm… can you give me the full stack trace their?

**Comment by eggyal** [comment]
TypeError: Arguments to path.resolve must be strings
        at Object.posix.resolve (path.js:439:13)
        at DestroyableTransform.saveFile [as _transform] (/path/to/project/node_modules/gulp/node_modules/vinyl-fs/lib/dest/index.js:36:26)
        at DestroyableTransform.Transform._read (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
        at DestroyableTransform.Transform._write (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
        at doWrite (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
        at writeOrBuffer (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
        at DestroyableTransform.Writable.write (/path/to/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
        at Labeled.ondata (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:572:20)
        at Labeled.emit (events.js:129:20)
        at readableAddChunk (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:195:16)
        at Labeled.Readable.push (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:162:10)
        at Labeled.Pipeline._read (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:56:31)
        at Labeled.onreadable (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:63:18)
        at Labeled.g (events.js:199:16)
        at Labeled.emit (events.js:104:17)
        at emitReadable_ (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:456:10)
        at emitReadable (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:450:7)
        at readableAddChunk (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:206:11)
        at Labeled.Readable.push (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:162:10)
        at Labeled.Pipeline._read (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:56:31)
        at Transform.onreadable (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:63:18)
        at Transform.g (events.js:199:16)
        at Transform.emit (events.js:104:17)
        at emitReadable_ (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
        at emitReadable (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
        at readableAddChunk (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
        at Transform.Readable.push (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
        at Transform.push (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
        at Transform.write [as _transform] (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/index.js:59:18)
        at Transform._read (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
        at Transform._write (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/watchify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
        at Labeled.Pipeline._write (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:72:22)
        at doWrite (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:279:12)
        at writeOrBuffer (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:266:5)
        at Labeled.Writable.write (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:211:11)
        at Labeled.ondata (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:572:20)
        at Labeled.emit (events.js:107:17)
        at readableAddChunk (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:195:16)
        at Labeled.Readable.push (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:162:10)
        at Labeled.Pipeline._read (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:56:31)
        at Transform.onreadable (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:63:18)
        at Transform.g (events.js:199:16)
        at Transform.emit (events.js:104:17)
        at emitReadable_ (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:448:10)
        at emitReadable (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:444:5)
        at readableAddChunk (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:187:9)
        at Transform.Readable.push (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:149:10)
        at Transform.push (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:145:32)
        at Transform.end [as _flush] (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/browser-pack/index.js:95:27)
        at Transform.<anonymous> (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:135:12)
        at Transform.g (events.js:199:16)
        at Transform.emit (events.js:129:20)
        at finishMaybe (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:371:12)
        at endWritable (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:378:3)
        at Transform.Writable.end (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:356:5)
        at Transform.onend (/path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:523:10)
        at Transform.g (events.js:199:16)
        at Transform.emit (events.js:129:20)
        at /path/to/project/node_modules/atomify/node_modules/atomify-js/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:965:16
        at process._tickCallback (node.js:355:11)

**Comment by eggyal** [comment]
Oh, that error was just because the stream returned by `atomic-js` isn't a vinyl file.  Once I piped through `vinyl-source-stream`, it's all okay now—your fix above did indeed work.

**Comment by joeybaker** [comment]
Okay! Great. I'll push it through.

**Comment by joeybaker** [comment]
Published in 4.7.2
